apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: starter-project
  description: Tanzu Application Platform - starter-project
  tags:
    - starter-project
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=starter-project'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
